version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: core-api
    environment:
      POSTGRES_DB: core_dev
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
